services:
    info_a:
        image: "stefanprodan/podinfo:5.2.1"
        ports:
            - "9001:9898"

    info_b:
        image: "stefanprodan/podinfo:5.2.1"
        ports:
            - "9002:9898"

            
    nginx:
        image: "nginx:1.20.1"
        volumes:
            - type: bind
              source: ./default.conf
              target: /etc/nginx/conf.d/default.conf        
        ports:
            - "8080:80"

