services:
    info_a:
        image: "stefanprodan/podinfo:5.2.1"
        environment:
            - VERSION=0.0.1        
        ports:
            - "9001:9898"
        command: [ "./podinfo", "--level=debug" ]            
        networks:
            - service_bridge

    info_b:
        image: "stefanprodan/podinfo:5.2.1"
        environment:
            - VERSION=0.0.2
        ports:
            - "9002:9898"
        command: [ "./podinfo", "--level=debug" ]  
        networks:
            - service_bridge

    nginx:
        image: "nginx:1.20.1"
        volumes:
            - type: bind
              source: ./default.conf
              target: /etc/nginx/conf.d/default.conf        
        ports:
            - "8080:80"
        networks:
            - service_bridge
            #- proxy_host       
    
    ubuntu:
        image: "ubuntu:21.04"
        command: [ "/bin/sh", "-c", "sleep infinity" ]  
        networks:
            - service_bridge
            #- proxy_host       

networks:
    service_bridge:
        driver: bridge

    #proxy_host:
    #    driver: host        